import Document from "../models/Document.js";
import Contract from "../models/Contract.js";
import Invoice from "../models/Invoice.js";
import OnboardingTimeline from "../models/OnboardingTimeline.js";
import PDFDocument from "pdfkit";
import path from "path";
import { fileURLToPath } from "url";

const BACKEND_URL = process.env.BACKEND_URL || "http://localhost:5000";

function urlToLocalPath(url) {
  return url
    .replace(BACKEND_URL, path.join(__dirname, ".."))
    .replace("http://localhost:5000", path.join(__dirname, ".."));
}

// ── Onboarding helpers ───────────────────────────────────────────────
async function ensureOnboarding(clientId) {
  let ob = await OnboardingTimeline.findOne({ clientId });
  if (!ob) ob = await OnboardingTimeline.create({ clientId });
  return ob;
}

async function markStep(clientId, key) {
  const ob = await ensureOnboarding(clientId);
  const step = ob.steps.find(s => s.key === key);
  if (step && !step.completed) {
    step.completed = true;
    step.completedAt = new Date();
    await ob.save();
  }
}

// ── HTML → plain text (preserves structure) ─────────────────────────
function htmlToLines(html = "") {
  return html
    .replace(/<h[1-3][^>]*>(.*?)<\/h[1-3]>/gi, "\n§HEADING§$1\n")
    .replace(/<li[^>]*>(.*?)<\/li>/gi, "  • $1\n")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<p[^>]*>(.*?)<\/p>/gi, "$1\n")
    .replace(/<strong[^>]*>(.*?)<\/strong>/gi, "$1")
    .replace(/<em[^>]*>(.*?)<\/em>/gi, "$1")
    .replace(/<u[^>]*>(.*?)<\/u>/gi, "$1")
    .replace(/<[^>]+>/g, "")
    .replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">")
    .replace(/&nbsp;/g, " ").replace(/&#39;/g, "'").replace(/&quot;/g, '"')
    .split("\n")
    .map(l => l.trim())
    .filter((l, i, arr) => l !== "" || (arr[i - 1] !== ""))  // collapse multiple blanks
    .join("\n");
}

// ── PDF builder ──────────────────────────────────────────────────────
function startPDF(res, filename) {
  const doc = new PDFDocument({ margin: 0, size: "A4", bufferPages: true });
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="${filename.replace(/[^a-z0-9]/gi, "_")}.pdf"`);
  doc.pipe(res);
  return doc;
}

const BRAND   = "#0e7490";
const DARK    = "#111827";
const MUTED   = "#6b7280";
const LIGHT   = "#f9fafb";
const BORDER  = "#e5e7eb";
const L = 50;          // left margin
const R = 545;         // right edge
const W = R - L;       // content width

function drawHeader(doc, title, subtitle = "") {
  // Teal banner
  doc.rect(0, 0, doc.page.width, 72).fill(BRAND);
  doc.fillColor("white").font("Helvetica-Bold").fontSize(18).text("Freelance Studio", L, 18);
  doc.font("Helvetica").fontSize(9).fillColor("rgba(255,255,255,0.75)").text(title, L, 42);
  if (subtitle) doc.text(subtitle, L, 54);
  doc.y = 90;
}

function drawFooter(doc) {
  const pages = doc.bufferedPageRange();
  for (let i = 0; i < pages.count; i++) {
    doc.switchToPage(pages.start + i);
    const y = doc.page.height - 36;
    doc.moveTo(L, y).lineTo(R, y).lineWidth(0.5).strokeColor(BORDER).stroke();
    doc.font("Helvetica").fontSize(7.5).fillColor(MUTED)
      .text(`Generated by Freelance Studio  ·  ${new Date().toLocaleString()}  ·  Page ${i + 1} of ${pages.count}`,
        L, y + 8, { width: W, align: "center" });
  }
}

function sectionHeading(doc, text) {
  doc.moveDown(0.6);
  doc.font("Helvetica-Bold").fontSize(10).fillColor(BRAND).text(text.toUpperCase(), L, doc.y, { width: W });
  doc.moveDown(0.15);
  doc.moveTo(L, doc.y).lineTo(R, doc.y).lineWidth(0.5).strokeColor(BORDER).stroke();
  doc.moveDown(0.35);
}

function bodyText(doc, text) {
  doc.font("Helvetica").fontSize(9.5).fillColor(DARK).text(text, L, doc.y, { width: W, lineGap: 3 });
  doc.moveDown(0.5);
}

function infoRow(doc, label, value) {
  const startY = doc.y;
  doc.font("Helvetica-Bold").fontSize(8.5).fillColor(MUTED).text(label, L, startY, { width: 110, continued: false });
  doc.font("Helvetica").fontSize(9).fillColor(DARK).text(value || "—", L + 115, startY, { width: W - 115 });
  doc.moveDown(0.3);
}

// ── CONTRACT PDF ─────────────────────────────────────────────────────
export async function generateContractPDF(req, res, next) {
  try {
    const contract = await Contract.findById(req.params.id);
    if (!contract) return res.status(404).json({ message: "Not found" });

    const doc = startPDF(res, `Contract_${contract.clientName || contract._id}`);
    drawHeader(doc, "Freelance Project Agreement",
      `Status: ${contract.status.toUpperCase()}  ·  Date: ${new Date(contract.createdAt).toLocaleDateString()}`);

    // Parties
    sectionHeading(doc, "Parties");
    infoRow(doc, "Client", `${contract.clientName}  ·  ${contract.clientEmail}`);
    contract.freelancers.forEach((f, i) => {
      infoRow(doc, `Freelancer ${contract.freelancers.length > 1 ? i + 1 : ""}`.trim(),
        `${f.name}  ·  ${f.role}  ·  ${f.email}${f.mobile ? "  ·  " + f.mobile : ""}`);
    });

    // Dates
    sectionHeading(doc, "Timeline");
    infoRow(doc, "Created",  new Date(contract.createdAt).toLocaleString());
    infoRow(doc, "Sent",     contract.sentAt   ? new Date(contract.sentAt).toLocaleString()   : "Not sent");
    infoRow(doc, "Viewed",   contract.viewedAt ? new Date(contract.viewedAt).toLocaleString() : "Not viewed");
    infoRow(doc, "Signed",   contract.signedAt ? new Date(contract.signedAt).toLocaleString() : "Pending");

    // Agreement body
    sectionHeading(doc, "Agreement");
    const lines = htmlToLines(contract.body);
    lines.split("\n").forEach(line => {
      if (line.startsWith("§HEADING§")) {
        doc.moveDown(0.4);
        doc.font("Helvetica-Bold").fontSize(10).fillColor(DARK).text(line.replace("§HEADING§", ""), L, doc.y, { width: W });
        doc.moveDown(0.2);
      } else if (line.startsWith("  •")) {
        doc.font("Helvetica").fontSize(9.5).fillColor(DARK).text(line, L + 8, doc.y, { width: W - 8, lineGap: 2 });
      } else if (line) {
        doc.font("Helvetica").fontSize(9.5).fillColor(DARK).text(line, L, doc.y, { width: W, lineGap: 3 });
      } else {
        doc.moveDown(0.4);
      }
    });

    // Signatures block
    doc.moveDown(1.5);
    sectionHeading(doc, "Signatures");

    const sigY = doc.y + 10;
    const colW = (W - 20) / 2;

    // Freelancer sig(s)
    contract.freelancers.forEach((f, i) => {
      const x = L + i * (colW + 20);
      if (f.signatureUrl) {
        try {
          const imgPath = urlToLocalPath(f.signatureUrl);
          doc.image(imgPath, x, sigY, { width: 120, height: 40, fit: [120, 40] });
        } catch { /* skip if image missing */ }
      }
      doc.moveTo(x, sigY + 50).lineTo(x + colW, sigY + 50).lineWidth(0.5).strokeColor(BORDER).stroke();
      doc.font("Helvetica").fontSize(8).fillColor(MUTED).text(`${f.name} (Freelancer)`, x, sigY + 54, { width: colW });
    });

    // Client sig
    const clientX = L + (contract.freelancers.length === 1 ? colW + 20 : 0);
    const clientSigX = contract.freelancers.length === 1 ? clientX : L;
    const clientSigY = contract.freelancers.length === 1 ? sigY : sigY + 80;

    if (contract.clientSignatureUrl) {
      try {
        const imgPath = urlToLocalPath(contract.clientSignatureUrl);
        doc.image(imgPath, clientSigX, clientSigY, { width: 120, height: 40, fit: [120, 40] });
      } catch { /* skip */ }
    }
    doc.moveTo(clientSigX, clientSigY + 50).lineTo(clientSigX + colW, clientSigY + 50)
      .lineWidth(0.5).strokeColor(BORDER).stroke();
    doc.font("Helvetica").fontSize(8).fillColor(MUTED)
      .text(`${contract.clientName} (Client)`, clientSigX, clientSigY + 54, { width: colW });

    if (contract.termsAccepted) {
      doc.moveDown(3);
      doc.font("Helvetica").fontSize(8).fillColor(MUTED)
        .text("✓ Client has read and agreed to the terms and conditions.", L, doc.y);
    }

    drawFooter(doc);
    doc.end();
  } catch (e) { next(e); }
}

// ── INVOICE PDF ──────────────────────────────────────────────────────
export async function generateInvoicePDF(req, res, next) {
  try {
    const invoice = await Invoice.findById(req.params.id);
    if (!invoice) return res.status(404).json({ message: "Not found" });

    const doc = startPDF(res, `Invoice_${invoice.invoiceNumber}`);
    drawHeader(doc, `Invoice  ${invoice.invoiceNumber}`,
      `Status: ${invoice.status.toUpperCase()}  ·  Date: ${new Date(invoice.createdAt).toLocaleDateString()}`);

    // Billing info
    sectionHeading(doc, "Billing Details");
    infoRow(doc, "Bill To",  `${invoice.clientName}  ·  ${invoice.clientEmail}`);
    infoRow(doc, "From",     `${invoice.freelancerName}${invoice.freelancerEmail ? "  ·  " + invoice.freelancerEmail : ""}`);
    infoRow(doc, "Due Date", invoice.dueDate ? new Date(invoice.dueDate).toLocaleDateString() : "Upon receipt");

    // Line items table
    sectionHeading(doc, "Services");
    const tableTop = doc.y;
    const cols = { desc: L, qty: L + 270, price: L + 330, total: L + 400 };

    // Table header
    doc.rect(L, tableTop, W, 20).fill("#f3f4f6");
    doc.font("Helvetica-Bold").fontSize(8.5).fillColor(MUTED);
    doc.text("Description",  cols.desc  + 4, tableTop + 6, { width: 260 });
    doc.text("Qty",          cols.qty   + 4, tableTop + 6, { width: 55, align: "center" });
    doc.text("Unit Price",   cols.price + 4, tableTop + 6, { width: 65, align: "right" });
    doc.text("Total",        cols.total + 4, tableTop + 6, { width: 95, align: "right" });
    doc.y = tableTop + 24;

    // Rows
    invoice.lineItems.forEach((item, i) => {
      const rowY = doc.y;
      if (i % 2 === 1) doc.rect(L, rowY - 2, W, 18).fill("#fafafa");
      doc.font("Helvetica").fontSize(9).fillColor(DARK);
      doc.text(item.description || "—", cols.desc + 4, rowY, { width: 260 });
      doc.text(String(item.quantity),   cols.qty  + 4, rowY, { width: 55, align: "center" });
      doc.text(`$${Number(item.unitPrice).toFixed(2)}`, cols.price + 4, rowY, { width: 65, align: "right" });
      doc.text(`$${(item.quantity * item.unitPrice).toFixed(2)}`, cols.total + 4, rowY, { width: 95, align: "right" });
      doc.y = rowY + 18;
    });

    // Totals box
    doc.moveDown(0.5);
    const totX = L + W - 200;
    const totW = 200;
    doc.rect(totX, doc.y, totW, invoice.taxRate > 0 ? 58 : 40).fill(LIGHT);
    const totY = doc.y + 8;
    doc.font("Helvetica").fontSize(9).fillColor(MUTED);
    doc.text("Subtotal:", totX + 8, totY, { width: 100 });
    doc.font("Helvetica-Bold").fillColor(DARK).text(`$${Number(invoice.subtotal).toFixed(2)}`, totX + 8, totY, { width: totW - 16, align: "right" });
    if (invoice.taxRate > 0) {
      doc.font("Helvetica").fillColor(MUTED).text(`Tax (${invoice.taxRate}%):`, totX + 8, totY + 16, { width: 100 });
      doc.font("Helvetica-Bold").fillColor(DARK).text(`$${Number(invoice.tax).toFixed(2)}`, totX + 8, totY + 16, { width: totW - 16, align: "right" });
    }
    const totalLineY = totY + (invoice.taxRate > 0 ? 32 : 16);
    doc.moveTo(totX + 8, totalLineY).lineTo(totX + totW - 8, totalLineY).lineWidth(0.5).strokeColor(BORDER).stroke();
    doc.font("Helvetica-Bold").fontSize(11).fillColor(BRAND)
      .text("Total:", totX + 8, totalLineY + 6, { width: 100 });
    doc.text(`$${Number(invoice.total).toFixed(2)}`, totX + 8, totalLineY + 6, { width: totW - 16, align: "right" });
    doc.y = totalLineY + 30;

    // Payment instructions
    if (invoice.paymentInstructions) {
      doc.moveDown(0.5);
      sectionHeading(doc, "Payment Instructions");
      bodyText(doc, invoice.paymentInstructions);
    }

    // Payment status
    if (invoice.paymentStatus === "confirmed") {
      doc.moveDown(0.3);
      doc.rect(L, doc.y, W, 28).fill("#f0fdf4");
      doc.font("Helvetica-Bold").fontSize(9.5).fillColor("#16a34a")
        .text(`✓ Payment Confirmed  ·  ${invoice.paymentConfirmedAt ? new Date(invoice.paymentConfirmedAt).toLocaleDateString() : ""}`,
          L + 10, doc.y + 9, { width: W - 20 });
      doc.y += 36;
    }

    if (invoice.notes) {
      doc.moveDown(0.3);
      sectionHeading(doc, "Notes");
      bodyText(doc, invoice.notes);
    }

    drawFooter(doc);
    doc.end();
  } catch (e) { next(e); }
}

// ── DOCUMENT PDF (welcome / thankyou) ────────────────────────────────
export async function generateDocumentPDF(req, res, next) {
  try {
    const document = await Document.findById(req.params.id).populate("clientId", "name surname email");
    if (!document) return res.status(404).json({ message: "Not found" });

    const typeLabel = document.type === "welcome" ? "Welcome Message" : "Thank You Note";
    const doc = startPDF(res, `${typeLabel}_${document.clientId?.name || document._id}`);
    drawHeader(doc, typeLabel,
      `To: ${document.clientId?.name || "Client"}  ·  ${new Date(document.createdAt).toLocaleDateString()}`);

    sectionHeading(doc, document.title);

    const lines = htmlToLines(document.content);
    lines.split("\n").forEach(line => {
      if (line.startsWith("§HEADING§")) {
        doc.moveDown(0.4);
        doc.font("Helvetica-Bold").fontSize(10.5).fillColor(DARK).text(line.replace("§HEADING§", ""), L, doc.y, { width: W });
        doc.moveDown(0.2);
      } else if (line.startsWith("  •")) {
        doc.font("Helvetica").fontSize(9.5).fillColor(DARK).text(line, L + 8, doc.y, { width: W - 8, lineGap: 2 });
      } else if (line) {
        doc.font("Helvetica").fontSize(9.5).fillColor(DARK).text(line, L, doc.y, { width: W, lineGap: 3 });
      } else {
        doc.moveDown(0.5);
      }
    });

    if (document.sentAt) {
      doc.moveDown(1);
      doc.font("Helvetica").fontSize(8).fillColor(MUTED)
        .text(`Sent: ${new Date(document.sentAt).toLocaleString()}`, L, doc.y);
    }

    drawFooter(doc);
    doc.end();
  } catch (e) { next(e); }
}

// ── DOCUMENTS ────────────────────────────────────────────────────────
export async function getDocuments(req, res, next) {
  try {
    const filter = {};
    if (req.query.clientId) filter.clientId = req.query.clientId;
    if (req.query.type)     filter.type     = req.query.type;
    if (req.query.status)   filter.status   = req.query.status;
    const docs = await Document.find(filter).populate("clientId", "name surname email").sort({ createdAt: -1 });
    res.json(docs);
  } catch (e) { next(e); }
}

export async function getDocumentById(req, res, next) {
  try {
    const doc = await Document.findById(req.params.id).populate("clientId", "name surname email");
    if (!doc) return res.status(404).json({ message: "Not found" });
    if (doc.status === "sent") { doc.status = "viewed"; doc.viewedAt = new Date(); await doc.save(); }
    res.json(doc);
  } catch (e) { next(e); }
}

export async function createDocument(req, res, next) {
  try { res.status(201).json(await Document.create(req.body)); }
  catch (e) { next(e); }
}

export async function updateDocument(req, res, next) {
  try {
    const doc = await Document.findByIdAndUpdate(req.params.id, req.body, { new: true });
    if (!doc) return res.status(404).json({ message: "Not found" });
    res.json(doc);
  } catch (e) { next(e); }
}

export async function deleteDocument(req, res, next) {
  try { await Document.findByIdAndDelete(req.params.id); res.json({ message: "Deleted" }); }
  catch (e) { next(e); }
}

export async function sendDocument(req, res, next) {
  try {
    const doc = await Document.findByIdAndUpdate(req.params.id, { status: "sent", sentAt: new Date() }, { new: true });
    if (!doc) return res.status(404).json({ message: "Not found" });
    const keyMap = { welcome: "welcome_sent", thankyou: "thankyou_sent" };
    if (keyMap[doc.type]) await markStep(doc.clientId, keyMap[doc.type]);
    res.json(doc);
  } catch (e) { next(e); }
}

// ── CONTRACTS ────────────────────────────────────────────────────────
export async function getContracts(req, res, next) {
  try {
    const filter = {};
    if (req.query.clientId) filter.clientId = req.query.clientId;
    if (req.query.status)   filter.status   = req.query.status;
    const contracts = await Contract.find(filter).populate("clientId", "name surname email").sort({ createdAt: -1 });
    res.json(contracts);
  } catch (e) { next(e); }
}

export async function getContractById(req, res, next) {
  try {
    const contract = await Contract.findById(req.params.id).populate("clientId", "name surname email");
    if (!contract) return res.status(404).json({ message: "Not found" });
    if (contract.status === "sent") { contract.status = "viewed"; contract.viewedAt = new Date(); await contract.save(); }
    res.json(contract);
  } catch (e) { next(e); }
}

export async function createContract(req, res, next) {
  try { res.status(201).json(await Contract.create(req.body)); }
  catch (e) { next(e); }
}

export async function updateContract(req, res, next) {
  try {
    const contract = await Contract.findByIdAndUpdate(req.params.id, req.body, { new: true });
    if (!contract) return res.status(404).json({ message: "Not found" });
    res.json(contract);
  } catch (e) { next(e); }
}

export async function sendContract(req, res, next) {
  try {
    const contract = await Contract.findByIdAndUpdate(req.params.id, { status: "sent", sentAt: new Date() }, { new: true });
    if (!contract) return res.status(404).json({ message: "Not found" });
    await markStep(contract.clientId, "contract_sent");
    res.json(contract);
  } catch (e) { next(e); }
}

export async function signContract(req, res, next) {
  try {
    const { clientSignatureUrl, termsAccepted } = req.body;
    if (!termsAccepted) return res.status(400).json({ message: "Terms must be accepted" });
    const contract = await Contract.findByIdAndUpdate(
      req.params.id,
      { status: "signed", signedAt: new Date(), clientSignatureUrl, termsAccepted },
      { new: true }
    );
    if (!contract) return res.status(404).json({ message: "Not found" });
    await markStep(contract.clientId, "contract_signed");
    res.json(contract);
  } catch (e) { next(e); }
}

// ── INVOICES ─────────────────────────────────────────────────────────
export async function getInvoices(req, res, next) {
  try {
    const filter = {};
    if (req.query.clientId) filter.clientId = req.query.clientId;
    if (req.query.status)   filter.status   = req.query.status;
    const invoices = await Invoice.find(filter).populate("clientId", "name surname email").sort({ createdAt: -1 });
    res.json(invoices);
  } catch (e) { next(e); }
}

export async function getInvoiceById(req, res, next) {
  try {
    const invoice = await Invoice.findById(req.params.id).populate("clientId", "name surname email");
    if (!invoice) return res.status(404).json({ message: "Not found" });
    res.json(invoice);
  } catch (e) { next(e); }
}

export async function createInvoice(req, res, next) {
  try { res.status(201).json(await Invoice.create(req.body)); }
  catch (e) { next(e); }
}

export async function updateInvoice(req, res, next) {
  try {
    const invoice = await Invoice.findByIdAndUpdate(req.params.id, req.body, { new: true });
    if (!invoice) return res.status(404).json({ message: "Not found" });
    res.json(invoice);
  } catch (e) { next(e); }
}

export async function sendInvoice(req, res, next) {
  try {
    const invoice = await Invoice.findByIdAndUpdate(req.params.id, { status: "pending" }, { new: true });
    if (!invoice) return res.status(404).json({ message: "Not found" });
    await markStep(invoice.clientId, "invoice_sent");
    res.json(invoice);
  } catch (e) { next(e); }
}

export async function confirmPayment(req, res, next) {
  try {
    const { paymentNote, paymentReceiptUrl } = req.body;
    const invoice = await Invoice.findByIdAndUpdate(
      req.params.id,
      {
        status: "paid",
        paymentStatus: "confirmed",
        paymentConfirmedAt: new Date(),
        paymentNote: paymentNote || "",
        paymentReceiptUrl: paymentReceiptUrl || "",
      },
      { new: true }
    );
    if (!invoice) return res.status(404).json({ message: "Not found" });
    await markStep(invoice.clientId, "payment_received");
    res.json(invoice);
  } catch (e) { next(e); }
}

// ── ONBOARDING TIMELINE ──────────────────────────────────────────────
export async function getOnboarding(req, res, next) {
  try { res.json(await ensureOnboarding(req.params.clientId)); }
  catch (e) { next(e); }
}

export async function updateOnboardingStep(req, res, next) {
  try {
    const { clientId, key, completed } = req.body;
    const ob = await ensureOnboarding(clientId);
    const step = ob.steps.find(s => s.key === key);
    if (!step) return res.status(404).json({ message: "Step not found" });
    step.completed = completed;
    step.completedAt = completed ? new Date() : undefined;
    await ob.save();
    res.json(ob);
  } catch (e) { next(e); }
}
